name: veritasad
description: VeritasAD Frontend
version: 1.0.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
