apiVersion: apps/v1
kind: Deployment
metadata:
  name: veritasad-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veritasad-redis
  template:
    metadata:
      labels:
        app: veritasad-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
